### ISSUE TITLE
Apk

### ISSUE THREAD

**Issue by aarvndhNG** [Leader-txt/TShockOnAndroid#1]
How do I use this apk?

**Comment by Leader-txt** [comment]
This project hasn't completed,you might wait for a serval times.

**Comment by LaoSparrow** [comment]
We are sorry but this project haven't been completed yet.
It may take weeks for us to finish this project, or months, who knows ;-;

**Comment by aarvndhNG** [comment]
> This project hasn't completed,you might wait for a serval times.

Oh i can't because i never tried tshock on mobile so interesting
